#!/bin/bash

CURRENT_DIRECTORY=`pwd`
REPO_PATH=${CURRENT_DIRECTORY}/..
JC2LI_PATH=${REPO_PATH}/jc2li
RPG_RUN_PATH=${CURRENT_DIRECTORY}/rpgrun
TEXT_PLAY_PATH=${CURRENT_DIRECTORY}/play/text
GRAPH_PLAY_PATH=${CURRENT_DIRECTORY}/play/graph
